using System.Diagnostics;
using System.Management;
using System.Net.NetworkInformation;
using Microsoft.Win32;
namespace RustPerformanceSuite.Services;
public sealed record OptimizationResult(string Category,string Action,bool Changed,string Details);
public sealed class OptimizationSuite
{
 readonly UndOptiRuntime _runtime=UndOptiRuntime.Instance;
 string Backup=>Path.Combine(_runtime.Root,"power-plan-backup.txt");
 public IReadOnlyList<OptimizationResult> OptimizeWindows(){var n=_runtime.Changes.Count;_runtime.ApplySafeProfile();return [new("Windows","Gaming profile",_runtime.Changes.Count>n,$"Tracked changes: {_runtime.Changes.Count-n}")];}
 public IReadOnlyList<OptimizationResult> OptimizeRust(){var r=OptimizeWindows().ToList();r.Add(SetRustPriority());return r;}
 public IReadOnlyList<OptimizationResult> CleanTempFiles(){var r=new List<OptimizationResult>();foreach(var d in new[]{Path.GetTempPath(),Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Temp")}){var n=0;try{if(Directory.Exists(d)){foreach(var f in Directory.EnumerateFiles(d,"*"))try{File.Delete(f);n++;}catch{}foreach(var s in Directory.EnumerateDirectories(d))try{Directory.Delete(s,true);n++;}catch{}}r.Add(new("Cleaner","Temporary files",n>0,$"Removed {n} item(s)"));}catch(Exception e){r.Add(new("Cleaner","Temporary files",false,e.Message));}}r.Add(CleanShaderCache());return r;}
 public OptimizationResult CleanShaderCache(){var d=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"D3DSCache");var n=0;try{if(!Directory.Exists(d))return new("Cleaner","Shader cache",false,"Cache directory not found.");foreach(var f in Directory.EnumerateFiles(d,"*"))try{File.Delete(f);n++;}catch{}return new("Cleaner","Shader cache",n>0,$"Removed {n} cached file(s).");}catch(Exception e){return new("Cleaner","Shader cache",false,e.Message);}}
 public OptimizationResult FlushDns(){try{using var p=Process.Start(new ProcessStartInfo("ipconfig.exe","/flushdns"){CreateNoWindow=true,UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true});if(p is null)return new("Network","Flush DNS",false,"Could not start ipconfig.");p.WaitForExit(8000);var o=p.StandardOutput.ReadToEnd().Trim();if(string.IsNullOrWhiteSpace(o))o=p.StandardError.ReadToEnd().Trim();return new("Network","Flush DNS",p.ExitCode==0,o);}catch(Exception e){return new("Network","Flush DNS",false,e.Message);}}
 public OptimizationResult SelectHighPerformancePowerPlan(){try{var s=new PowerPlanService();if(!File.Exists(Backup)){var g=s.GetActiveScheme();if(g.Length>0)File.WriteAllText(Backup,g);}var ok=s.SetHighPerformance();return new("Power","High performance",ok,ok?"High performance selected; previous plan saved.":"High performance plan was not available.");}catch(Exception e){return new("Power","High performance",false,e.Message);}}
 public OptimizationResult RestorePowerPlan(){try{if(!File.Exists(Backup))return new("Power","Restore",false,"No saved plan.");var g=File.ReadAllText(Backup).Trim();var ok=new PowerPlanService().Restore(g);if(ok)File.Delete(Backup);return new("Power","Restore",ok,ok?"Previous power plan restored.":"Could not restore the previous plan.");}catch(Exception e){return new("Power","Restore",false,e.Message);}}
 public OptimizationResult SetRustPriority(){try{var ps=Process.GetProcessesByName("RustClient_Win64").Concat(Process.GetProcessesByName("RustClient")).ToArray();if(ps.Length==0)return new("Rust","Priority",false,"Rust is not running.");var n=0;foreach(var p in ps){try{if(p.PriorityClass!=ProcessPriorityClass.AboveNormal){p.PriorityClass=ProcessPriorityClass.AboveNormal;n++;}}catch{}finally{p.Dispose();}}return new("Rust","Priority",n>0,$"AboveNormal applied to {n} process(es); session-only.");}catch(Exception e){return new("Rust","Priority",false,e.Message);}}
 public string StartupReport(){var a=new List<string>();foreach(var r in new[]{Registry.CurrentUser,Registry.LocalMachine})try{using var k=r.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run");if(k!=null)foreach(var n in k.GetValueNames())a.Add($"{(r==Registry.CurrentUser?"User":"Machine")}: {n} = {k.GetValue(n)}");}catch{}return a.Count==0?"No classic Run startup entries found.":string.Join(Environment.NewLine,a);}
 public string NetworkReport(){var a=new List<string>();foreach(var n in NetworkInterface.GetAllNetworkInterfaces())if(n.NetworkInterfaceType!=NetworkInterfaceType.Loopback)a.Add($"{n.Name} — {n.NetworkInterfaceType} — {n.OperationalStatus} — {n.Speed/1000000d:0} Mbps");try{using var p=new Ping();var q=p.Send("1.1.1.1",1200);a.Add(q.Status==IPStatus.Success?$"1.1.1.1 latency: {q.RoundtripTime} ms":$"Ping: {q.Status}");}catch(Exception e){a.Add("Ping unavailable: "+e.Message);}return string.Join(Environment.NewLine,a);}
 public string AdvancedHardwareReport(){try{using var c=new ManagementObjectSearcher("SELECT Name,NumberOfCores,NumberOfLogicalProcessors,MaxClockSpeed FROM Win32_Processor");using var b=new ManagementObjectSearcher("SELECT Manufacturer,Product FROM Win32_BaseBoard");using var g=new ManagementObjectSearcher("SELECT Name,DriverVersion FROM Win32_VideoController");var x=c.Get().Cast<ManagementObject>().FirstOrDefault();var y=b.Get().Cast<ManagementObject>().FirstOrDefault();var z=g.Get().Cast<ManagementObject>().FirstOrDefault();return $"CPU: {x?["Name"]}\nCores/Threads: {x?["NumberOfCores"]}/{x?["NumberOfLogicalProcessors"]}\nMax clock: {x?["MaxClockSpeed"]} MHz\nBoard: {y?["Manufacturer"]} {y?["Product"]}\nGPU: {z?["Name"]}\nDriver: {z?["DriverVersion"]}\n\nBIOS/OC advisor: XMP/EXPO and vendor CPU/GPU tuning can be checked manually. UndOpti does not flash BIOS or write blind voltage/clock values.";}catch(Exception e){return "Hardware scan failed: "+e.Message;}}
 public string PerformanceRecommendations(){var h=new HardwareAnalyzer().Analyze();var a=new List<string>{"Apply gaming tweaks, then compare FPS and frametime.","Keep GPU drivers current when troubleshooting stutter.","Prefer stable frametimes over peak FPS in Rust.","Do not disable Windows security or EAC protections for performance."};if(h.RamGb<16)a.Add("RAM is below 16 GB; capacity may limit Rust plus background apps.");return string.Join(Environment.NewLine,a.Select(x=>"• "+x));}
}